# Generated by Django 4.2.6 on 2024-11-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
